const predefinedTemplates = [
    {
      id: 0,
      predefinedTemplateNumber: 0,
      f: 0.6,
      m: 70,
      n: 50,
    },
    {
      id: 1,
      predefinedTemplateNumber: 1,
      f: 2,
      m: 100,
      n: 10,
    },
    {
      id: 2,
      predefinedTemplateNumber: 2,
      f: -0.9,
      m: 47,
      n: 26,
    },
    {
      id: 3,
      predefinedTemplateNumber: 3,
      f: -1.1,
      m: 64,
      n: 12,
    },
    {
      id: 4,
      predefinedTemplateNumber: 4,
      f: 0.4,
      m: 26,
      n: 16,
    },
    {
      id: 5,
      predefinedTemplateNumber: 5,
      f: 0.62,
      m: 64,
      n: 46,
    },
    {
      id: 6,
      predefinedTemplateNumber: 6,
      f: -1.1,
      m: 19,
      n: 13,
    },
    {
      id: 7,
      predefinedTemplateNumber: 7,
      f: 0.4,
      m: 54,
      n: 16,
    },
    {
      id: 8,
      predefinedTemplateNumber: 8,
      f: 0.62,
      m: 90,
      n: 34,
    },
    {
      id: 9,
      predefinedTemplateNumber: 9,
      f: -1.1,
      m: 19,
      n: 13,
    },
    {
      id: 10,
      predefinedTemplateNumber: 10,
      f: 0.4,
      m: 54,
      n: 16,
    },
    {
      id: 11,
      predefinedTemplateNumber: 11,
      f: 0.62,
      m: 90,
      n: 34,
    },
    {
      id: 12,
      predefinedTemplateNumber: 12,
      f: 0.62,
      m: 90,
      n: 34,
    },
    {
      id: 13,
      predefinedTemplateNumber: 13,
      f: 0.62,
      m: 90,
      n: 34,
    },
    {
      id: 14,
      predefinedTemplateNumber: 14,
      f: 0.62,
      m: 90,
      n: 34,
    },
  ];

export default predefinedTemplates;